name: flutter_rating_bar_example
description: Demonstrates how to use the flutter_rating_bar plugin.
publish_to: 'none'

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_rating_bar:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
